### ISSUE TITLE
NPC stats Script delay

### ISSUE THREAD

**Issue by arosenow** [UnearthedArcana/NPC_EE#9]
After using the book your kit is immediately changed and you may level up.
A short while later the script sets HP to 2 and asks to revise your stats, but as this is after a delay you may have already levelled up, nerfing your npc. 
I had assumed this was a bug, but now I'm aware I need to wait for the stats script to run before I level up, otherwise I am using the mod incorrectly

**Comment by subtledoctor** [comment]
I'm confused by "kit changes, then asks to revise stats." That... can't happen?

If you change your *class,* then it should pop up a message that says "please be patient etc."

If you are only changing your kit, then no more changes should happen and this would be a major bug.

**Comment by arosenow** [comment]
Sorry used the wrong word, I meant class. 
The prompt didn't seem to come up to be aware it was still thinking.

It seems if I don't install NPC_EE absolutely last conflicts can happen eg HP is reset to 2 a minute later without a prompt and the advanced ai starts flicking on and off.

**Comment by arosenow** [comment]
I did some further testing, it appears that the version that the EET installer software downloads has the bug that breaks the advanced AI.
When I use 5.7.1 directly from github I don't encounter the issue.

**Comment by subtledoctor** [comment]
The "EE Mod Setup Tool" is software is an undocumented rip-off of the old BWS app and its maintainer is known for not respecting other mod developers' work.  She has stolen work and put it up for download claiming ownership, and has cloned all sorts of mods and made unknown changes to them, and has the "Setup Tool" downloading her own ripoff versions instead of the actual mods. It's a sad situation but unfortunately you cannot trust that junk. Install mods yourself, or use the Big World .bat installer, or use Project Infinity.
